monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['request', 'security', 'event', 'console']
        logger_buffer:
            type: buffer
            buffer_size: 100
            handler: app_insights
            channels: ['!request', '!security', '!event', '!console']
        app_insights:
            type: service
            id: "app_insights_php.monolog.handler.trace"
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
