monolog:
    handlers:
        logger_buffer:
            type: buffer
            buffer_size: 100
            handler: app_insights
            level: error
        app_insights:
            type: service
            id: "app_insights_php.monolog.handler.trace"
